test:
		-$(PYTHON) testtest.py
		$(PYTHON) testcore.py
		$(PYTHON) testbuffer.py
		$(PYTHON) testbuffered.py
		$(PYTHON) teststackless.py
		$(PYTHON) testdeque.py
		$(PYTHON) testdequedict.py
		$(PYTHON) testhttp.py
		$(PYTHON) testio.py
		$(PYTHON) testlocal.py
		$(PYTHON) testpool.py
		$(PYTHON) teststatistic.py
		$(PYTHON) testmysql.py
		$(PYTHON) testtimer.py
		$(PYTHON) testmemcache.py
		$(PYTHON) testweb.py
		$(PYTHON) testremote.py

